### ISSUE TITLE
Documentation lacking

### ISSUE THREAD

**Issue by jsiddharth** [sensu-plugins/sensu-plugins-logs#14]
I wonder why all sensu plugins have this common issue in them. Documentation is so lacking. How can a documentation just have 3 lines in it for 4 commands that are provided ? How come the options and tricks and tips are just not mentioned ? We have to google like crazy to find anything regarding the plugin.

You have 4 files 
bin/check-journal.rb
bin/check-log.rb
bin/handler-logevent.rb
bin/handler-show-event-config.rb

And your doc has
{
  "logevent": {
    "eventdir": "/var/log/sensu/events",
    "keep": 10
  }
}

What am I missing, why isn't anyone else complaining. I am sure I am missing something really silly here. I found something useful in a issue, https://github.com/sensu-plugins/sensu-plugins-logs/issues/1

Sorry to sound so frustrated, but all sensu plugins have the EXACT same issue. Each and every one of them. Please correct me if I am wrong here.

**Comment by jsiddharth** [comment]
I need the documentation to start with
How to install this gem (dont point to the general documentation)
Usual scenarios for using each file, and examples

Please understand that people using tools like sensu, dont care about learning ruby. All we care about is our own business. 

Sensu is the "only" great tool that we like to use.

**Comment by jsiddharth** [comment]
I have copied the rb files to /etc/sensu/plugins folder, In the config.json I have
"check_log_for_fatal": {
        "command": "sudo check-log.rb -f /var/log/auth.log -q 'fatal' -c 1",
        "interval": 10,
        "subscribers": ["test"]
    },
    "check_log_for_invalid_user": {
        "command": "check-log.rb -f /var/log/auth.log -q 'Invalid user' -c 1",
        "interval": 10,
        "subscribers": ["test"]
    },


But I dont see these check's on uchiwa, what can be the issue ?

**Comment by GhostLyrics** [comment]
We are working on the documentation issue. Here's an example how the new style docs look: https://github.com/sensu-plugins/sensu-plugins-nvidia

However, this is a lot of work and will take time from volunteers. :)
If you're curious, here are the templates that are used to keep the new docs consistent: https://github.com/GhostLyrics/sensu-plugin-doc-draft

For more direct support you might want to stop by in the #sensu IRC on Freenode. (I say this because I don't see anything *wrong* in the JSON you posted.
